version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://user:password@postgres:5432/codeduck
    ports:
      - "4001:4000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/codeduck
      REDIS_URL: redis://redis:6379

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codeduck
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
