services:
  # Node.js backend API
  - type: web
    name: codeduck-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: codeduck-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: codeduck-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: "3000"

  # Redis cache/queue
  - type: keyvalue
    name: codeduck-redis
    plan: free
    ipAllowList: []

databases:
  # PostgreSQL database
  - name: codeduck-postgres
    plan: free