services:
  - type: web
    name: backend
    env: node
    repo: https://github.com/YOUR_USERNAME/code-duck.git # Replace with your repo URL
    branch: main
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: NODE_VERSION
        value: 18

  - type: psql
    name: postgres
    ipAllowList: [] # Allow all IPs to connect
